export const types = {
    // Auth
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    SAVE_LOGIN: 'SAVE_LOGIN',
    SAVE_PROFILE: 'SAVE_PROFILE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',

    CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

    CHANGE_INFORMATION_REQUEST: 'CHANGE_INFORMATION_REQUEST',
    CHANGE_INFORMATION_SUCCESS: 'CHANGE_INFORMATION_SUCCESS',
    CHANGE_INFORMATION_FAILURE: 'CHANGE_INFORMATION_FAILURE',

    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

    CONFIRM_FORGOT_REQUEST: 'CONFIRM_FORGOT_REQUEST',
    CONFIRM_FORGOT_SUCCESS: 'CONFIRM_FORGOT_SUCCESS',
    CONFIRM_FORGOT_FAILURE: 'CONFIRM_FORGOT_FAILURE',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    REMOVE_AUTH_RESULT: 'REMOVE_AUTH_RESULT',

    DELETE_ACCOUNT_REQUEST: 'DELETE_ACCOUNT_REQUEST',
    DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
    DELETE_ACCOUNT_FAILURE: 'DELETE_ACCOUNT_FAILURE',

    REMOVE_DELETE: 'REMOVE_DELETE',

    // Category
    GET_BANNER_CATEGORY_REQUEST: 'GET_BANNER_CATEGORY_REQUEST',
    GET_BANNER_CATEGORY_SUCCESS: 'GET_BANNER_CATEGORY_SUCCESS',
    GET_BANNER_CATEGORY_FAILURE: 'GET_BANNER_CATEGORY_FAILURE',

    REMOVE_CATEGORY_RESULT: 'REMOVE_CATEGORY_RESULT',

    // Post
    GET_LIST_POSTS_REQUEST: 'GET_LIST_POSTS_REQUEST',
    GET_LIST_POSTS_SUCCESS: 'GET_LIST_POSTS_SUCCESS',
    GET_LIST_POSTS_FAILURE: 'GET_LIST_POSTS_FAILURE',

    GET_POST_DETAIL_REQUEST: 'GET_POST_DETAIL_REQUEST',
    GET_POST_DETAIL_SUCCESS: 'GET_POST_DETAIL_SUCCESS',
    GET_POST_DETAIL_FAILURE: 'GET_POST_DETAIL_FAILURE',

    REMOVE_POST_RESULT: 'REMOVE_POST_RESULT',

    // Form
    FORM_BASE_REQUEST: 'FORM_BASE_REQUEST',
    FORM_BASE_SUCCESS: 'FORM_BASE_SUCCESS',
    FORM_BASE_FAILURE: 'FORM_BASE_FAILURE',

    CREATE_FORM_TRANSPORT_REQUEST: 'CREATE_FORM_TRANSPORT_REQUEST',
    CREATE_FORM_TRANSPORT_SUCCESS: 'CREATE_FORM_TRANSPORT_SUCCESS',
    CREATE_FORM_TRANSPORT_FAILURE: 'CREATE_FORM_TRANSPORT_FAILURE',

    REMOVE_FORM: 'REMOVE_FORM',

    // Abroad
    GET_LIST_ABROAD_REQUEST: 'GET_LIST_ABROAD_REQUEST',
    GET_LIST_ABROAD_SUCCESS: 'GET_LIST_ABROAD_SUCCESS',
    GET_LIST_ABROAD_FAILURE: 'GET_LIST_ABROAD_FAILURE',

    GET_DETAIL_ABROAD_REQUEST: 'GET_DETAIL_ABROAD_REQUEST',
    GET_DETAIL_ABROAD_SUCCESS: 'GET_DETAIL_ABROAD_SUCCESS',
    GET_DETAIL_ABROAD_FAILURE: 'GET_DETAIL_ABROAD_FAILURE',

    REMOVE_ABROAD_RESULT: 'REMOVE_ABROAD_RESULT',

    // Question
    CREATE_QUESTION_REQUEST: 'CREATE_QUESTION_REQUEST',
    CREATE_QUESTION_SUCCESS: 'CREATE_QUESTION_SUCCESS',
    CREATE_QUESTION_FAILURE: 'CREATE_QUESTION_FAILURE',

    GET_LIST_QUESTION_REQUEST: 'GET_LIST_QUESTION_REQUEST',
    GET_LIST_QUESTION_SUCCESS: 'GET_LIST_QUESTION_SUCCESS',
    GET_LIST_QUESTION_FAILURE: 'GET_LIST_QUESTION_FAILURE',

    GET_COUNT_QUESTION_REQUEST: 'GET_COUNT_QUESTION_REQUEST',
    GET_COUNT_QUESTION_SUCCESS: 'GET_COUNT_QUESTION_SUCCESS',
    GET_COUNT_QUESTION_FAILURE: 'GET_COUNT_QUESTION_FAILURE',

    // Menu
    GET_LIST_MENU_REQUEST: 'GET_LIST_MENU_REQUEST',
    GET_LIST_MENU_SUCCESS: 'GET_LIST_MENU_SUCCESS',
    GET_LIST_MENU_FAILURE: 'GET_LIST_MENU_FAILURE',

    REMOVE_MENU: 'REMOVE_MENU',
}