export const types = {
    // Auth
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    SAVE_LOGIN: 'SAVE_LOGIN',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',

    REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',

    CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

    CHANGE_INFORMATION_REQUEST: 'CHANGE_INFORMATION_REQUEST',
    CHANGE_INFORMATION_SUCCESS: 'CHANGE_INFORMATION_SUCCESS',
    CHANGE_INFORMATION_FAILURE: 'CHANGE_INFORMATION_FAILURE',

    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

    CONFIRM_FORGOT_REQUEST: 'CONFIRM_FORGOT_REQUEST',
    CONFIRM_FORGOT_SUCCESS: 'CONFIRM_FORGOT_SUCCESS',
    CONFIRM_FORGOT_FAILURE: 'CONFIRM_FORGOT_FAILURE',
}